//! Export functionality for molecular structures
//!
//! Provides methods to export molecules to standard file formats:
//! - PDB (Protein Data Bank format with fixed-width columns)
//! - XYZ (Simple Cartesian coordinates format)
//! - CIF (Crystallographic Information File, round-trip compatible)

use crate::molecule::Molecule;

/// Export a molecule to PDB format
///
/// PDB format specification (fixed-width columns):
/// - Columns 1-6: "ATOM  " (record type)
/// - Columns 7-11: Serial number (5 chars, right-aligned)
/// - Column 13-16: Atom name (4 chars, left-aligned)
/// - Column 18-20: Residue name (3 chars)
/// - Column 22: Chain ID (1 char)
/// - Columns 23-26: Residue sequence number (4 chars)
/// - Columns 31-38: X coordinate (8 chars, F8.3 format)
/// - Columns 39-46: Y coordinate (8 chars, F8.3 format)
/// - Columns 47-54: Z coordinate (8 chars, F8.3 format)
/// - Columns 55-60: Occupancy (6 chars, F6.2 format, default 1.00)
/// - Columns 61-66: Temperature factor (6 chars, F6.2 format, default 0.00)
/// - Columns 77-78: Element symbol (2 chars, right-aligned)
pub fn export_pdb(molecule: &Molecule, name: &str) -> String {
    let mut output = String::new();

    // HEADER record
    output.push_str(&format!("HEADER    {}                                                           \n", name));
    output.push_str("TITLE     EXPORTED FROM AXIOM MOLECULAR VIEWER                             \n");
    output.push_str("REMARK    Generated by Axiom v0.3.0                                        \n");

    // ATOM records
    for (i, atom) in molecule.atoms.iter().enumerate() {
        let serial = i + 1;
        let atom_name = &atom.element;
        let res_name = "MOL"; // Generic residue name
        let chain = 'A';
        let res_seq = 1;
        let x = atom.position[0];
        let y = atom.position[1];
        let z = atom.position[2];
        let occupancy = 1.00;
        let temp_factor = 0.00;

        // Format PDB line with exact column positions
        // "ATOM  " = 6 chars, serial = 5 chars, atom_name = 4 chars (with space padding)
        output.push_str(&format!(
            "ATOM  {:>5} {:4} {:3} {:1}{:>4}    {:>8.3}{:>8.3}{:>8.3}{:>6.2}{:>6.2}          {:>2}\n",
            serial, atom_name, res_name, chain, res_seq, x, y, z, occupancy, temp_factor, atom.element
        ));
    }

    // END record
    output.push_str("END\n");

    output
}

/// Export a molecule to XYZ format
///
/// XYZ format specification:
/// Line 1: Number of atoms
/// Line 2: Comment line (structure name)
/// Lines 3+: Element symbol, X, Y, Z coordinates (space-separated)
pub fn export_xyz(molecule: &Molecule, name: &str) -> String {
    let mut output = String::new();

    // Line 1: atom count
    output.push_str(&format!("{}\n", molecule.atoms.len()));

    // Line 2: comment (structure name)
    output.push_str(&format!("{}\n", name));

    // Lines 3+: atom data
    for atom in &molecule.atoms {
        output.push_str(&format!(
            "{:2} {:>12.6} {:>12.6} {:>12.6}\n",
            atom.element,
            atom.position[0],
            atom.position[1],
            atom.position[2]
        ));
    }

    output
}

/// Export a molecule to CIF format
///
/// Generates a minimal CIF file with atom_site loop
/// Note: This is a simplified export that preserves atom information
/// but does not round-trip all CIF metadata (symmetry, cell params, etc.)
pub fn export_cif(molecule: &Molecule, name: &str) -> String {
    let mut output = String::new();

    // Data block header
    output.push_str(&format!("data_{}\n", name.replace(' ', "_")));
    output.push_str("#\n");
    output.push_str("# Generated by Axiom Molecular Viewer v0.3.0\n");
    output.push_str("#\n\n");

    // Cell parameters (use bounding box as a pseudo-cell)
    let bounds = molecule.bounds;
    let a = bounds[3] - bounds[0]; // width
    let b = bounds[4] - bounds[1]; // height
    let c = bounds[5] - bounds[2]; // depth

    output.push_str(&format!("_cell_length_a    {:.3}\n", a.max(1.0)));
    output.push_str(&format!("_cell_length_b    {:.3}\n", b.max(1.0)));
    output.push_str(&format!("_cell_length_c    {:.3}\n", c.max(1.0)));
    output.push_str("_cell_angle_alpha 90.000\n");
    output.push_str("_cell_angle_beta  90.000\n");
    output.push_str("_cell_angle_gamma 90.000\n");
    output.push('\n');

    // Symmetry (default to P1)
    output.push_str("_symmetry_space_group_name_H-M 'P 1'\n");
    output.push_str("_symmetry_Int_Tables_number    1\n");
    output.push('\n');

    // Atom site loop
    output.push_str("loop_\n");
    output.push_str("_atom_site_label\n");
    output.push_str("_atom_site_type_symbol\n");
    output.push_str("_atom_site_fract_x\n");
    output.push_str("_atom_site_fract_y\n");
    output.push_str("_atom_site_fract_z\n");

    // Convert Cartesian coordinates to fractional (relative to bounding box)
    for (i, atom) in molecule.atoms.iter().enumerate() {
        let label = format!("{}{}", atom.element, i + 1);

        // Fractional coordinates (0-1 range within bounding box)
        let fx = if a > 0.0 { (atom.position[0] - bounds[0]) / a } else { 0.5 };
        let fy = if b > 0.0 { (atom.position[1] - bounds[1]) / b } else { 0.5 };
        let fz = if c > 0.0 { (atom.position[2] - bounds[2]) / c } else { 0.5 };

        output.push_str(&format!(
            "{:6} {:2} {:>8.5} {:>8.5} {:>8.5}\n",
            label, atom.element, fx, fy, fz
        ));
    }

    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::molecule::MoleculeAtom;

    fn create_test_molecule() -> Molecule {
        Molecule {
            atoms: vec![
                MoleculeAtom {
                    element: "C".to_string(),
                    label: "C1".to_string(),
                    position: [0.0, 0.0, 0.0],
                    radius: 0.70,
                    color: [0.5, 0.5, 0.5],
                },
                MoleculeAtom {
                    element: "O".to_string(),
                    label: "O1".to_string(),
                    position: [1.5, 0.0, 0.0],
                    radius: 0.60,
                    color: [1.0, 0.0, 0.0],
                },
            ],
            bonds: vec![],
            bounds: [0.0, 0.0, 0.0, 1.5, 0.0, 0.0],
        }
    }

    #[test]
    fn test_export_pdb_structure() {
        let molecule = create_test_molecule();
        let pdb = export_pdb(&molecule, "test");

        // Verify HEADER is present
        assert!(pdb.contains("HEADER"));

        // Verify ATOM records
        assert!(pdb.contains("ATOM"));

        // Verify both atoms are present
        assert!(pdb.contains("C"));
        assert!(pdb.contains("O"));

        // Verify END record
        assert!(pdb.ends_with("END\n"));

        // Count ATOM lines (should be 2)
        let atom_count = pdb.lines().filter(|l| l.starts_with("ATOM")).count();
        assert_eq!(atom_count, 2);
    }

    #[test]
    fn test_export_xyz_format() {
        let molecule = create_test_molecule();
        let xyz = export_xyz(&molecule, "test molecule");

        let lines: Vec<&str> = xyz.lines().collect();

        // Line 1: atom count
        assert_eq!(lines[0], "2");

        // Line 2: comment
        assert_eq!(lines[1], "test molecule");

        // Lines 3-4: atoms (note: element symbols are left-aligned in 2-char field)
        assert!(lines[2].starts_with("C "));
        assert!(lines[3].starts_with("O "));

        // Verify coordinates are present
        assert!(lines[2].contains("0.000000"));
        assert!(lines[3].contains("1.500000"));
    }

    #[test]
    fn test_export_cif_structure() {
        let molecule = create_test_molecule();
        let cif = export_cif(&molecule, "test");

        // Verify data block
        assert!(cif.contains("data_test"));

        // Verify cell parameters
        assert!(cif.contains("_cell_length_a"));
        assert!(cif.contains("_cell_length_b"));
        assert!(cif.contains("_cell_length_c"));

        // Verify atom_site loop
        assert!(cif.contains("loop_"));
        assert!(cif.contains("_atom_site_label"));
        assert!(cif.contains("_atom_site_type_symbol"));

        // Verify atoms are present (labels are formatted as C1, O2, etc.)
        assert!(cif.contains("C1"));
        assert!(cif.contains("O2")); // Second atom gets index 2
    }

    #[test]
    fn test_pdb_fixed_width_columns() {
        let molecule = create_test_molecule();
        let pdb = export_pdb(&molecule, "test");

        // Find first ATOM line
        let atom_line = pdb.lines()
            .find(|l| l.starts_with("ATOM"))
            .expect("No ATOM line found");

        // Verify line is at least 66 characters (minimum PDB line length)
        assert!(atom_line.len() >= 66);

        // Verify "ATOM  " is in columns 1-6
        assert_eq!(&atom_line[0..6], "ATOM  ");

        // Verify coordinates are in correct columns (31-54)
        // The format uses F8.3, so coordinates should be right-aligned
        let coord_section = &atom_line[30..54]; // Columns 31-54 (0-indexed)
        assert!(coord_section.contains('.'));
    }
}
